Blended program fixes 4.8.4
sunbird-cb/sunbird-course-service pull request #57
Opened 2023-06-20 10:03 UTC by juhiagl8

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### Type of change

Please choose appropriate options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Ran Test A
- [ ] Ran Test B

**Test Configuration**:
* Software versions: Java-11, play2-2.7.2, scala-2.11, redis-5.0.3
* Hardware versions: 2 CPU / 4GB RAM

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-06-20 11:53 UTC, karthik-tarento requested changes

2023-06-20 11:53 UTC, karthik-tarento commented on course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/responsecode/ResponseMessage.java
> +    String CURRENT_BATCH_SIZE_PARAMETER = "currentBatchSize param missing in request. Please check the incoming request";
Request body is missing parameter 'currentBatchSize' in batchAttributes.

2023-06-20 11:53 UTC, karthik-tarento commented on course-mw/course-actors-common/src/main/java/org/sunbird/learner/actors/certificate/service/CourseBatchCertificateActor.java
> +    }
this requires changes in mapToObject method too...

2023-06-20 11:53 UTC, karthik-tarento commented on course-mw/course-actors/src/main/java/org/sunbird/learner/actors/coursebatch/CourseBatchManagementActor.java
> +    }
this requires changes in mapToObject method too.

2023-06-20 11:53 UTC, karthik-tarento commented on course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/responsecode/ResponseMessage.java
> +    String CURRENT_BATCH_SIZE_MISSING =  "CURRENT_BATCH_SIZE_MISSING";
MISSING_FIELD_CURRENT_BATCH_SIZE

2023-06-22 05:39 UTC, karthik-tarento approved these changes

2023-06-22 05:39 UTC, merged

2023-06-22 05:44 UTC, wilkysingh-tarento commented on course-mw/course-actors/src/main/java/org/sunbird/learner/actors/coursebatch/CourseBatchManagementActor.java
> +    if (JsonKey.PRIMARY_CATEGORY_BLENDED_PROGRAM.equalsIgnoreCase(primaryCategory) && courseBatch.getBatchAttributes().get(JsonKey.CURRENT_BATCH_SIZE) == null) {
Add one more condition that currentBatchSize must be greater than 0 if present

2023-06-22 05:44 UTC, wilkysingh-tarento commented on course-mw/course-actors/src/main/java/org/sunbird/learner/actors/coursebatch/CourseBatchManagementActor.java
> +      ProjectCommonException.throwClientErrorException(
Please check are we using this common exception already